version: '3'
services:

  #APP SERVICES
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code_igniter_skeleton
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - ci_skeleton

  #NGINX SERVICES
  nginx:
    image: nginx:alpine
    container_name: code_igniter_skeleton_http
    restart: unless-stopped
    tty: true
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - ci_skeleton

  #MYSQL SERVICES
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: code_igniter_skeleton_db
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: unless-stopped
    ports:
      - 3319:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: code_igniter_skeleton
    networks:
      - ci_skeleton

#DOCKER NETWORKS
networks:
  ci_skeleton:
    driver: bridge