name: CI Check
run-name: ${{ github.actor }} Push Update

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Menggunakan Node.js versi 16
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
            php-version: '7.4'

      - name: composer manifest package validation
        run: composer validate --strict
        
      - name: install composer dependencies
        run: composer install